name: Clear PR Comment

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  clear-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clear original PR comment
      uses: actions/github-script@v6
      with:
        script: |
          console.log('OWNER', context.repo.owner);
          console.log('REPO', context.repo.repo);
          console.log('fullContext', context)
          console.log('PRContext', context.payload.pull_request)
