name: Clear PR Comment

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  clear-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clear original PR comment
      uses: actions/github-script@v6
      with:
        script: |

          const prNumber = context.payload.pull_request.number;
          const commits = await github.rest.pulls.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber});

          const lineTemplate = `- [ ] [BRANCH_NAME](https://testorg.atlassian.net/browse/BRANCH_NAME) @USER`

          const filteredCommsfordebug = commits.data
          .filter(commitObject => commitObject.commit.message.startsWith('Merge pull request'))

          console.log(filteredCommsfordebug[0])

          const newPRContent = commits.data
          .filter(commitObject => commitObject.commit.message.startsWith('Merge pull request'))
          .map(x => {
          const author = x.author.login

          const branchName = x.commit.message.split('/')[1]

          const newLine = lineTemplate.replace('USER',author).replace('BRANCH_NAME', branchName).replace('BRANCH_NAME', branchName)
          console.log('newLine', newLine)

          return newLine})
          console.log(newPRContent, 'newPRContent')


          

    
