name: Clear PR Comment

on:
  pull_request:
    types: [opened]

jobs:
  clear-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clear original PR comment
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          console.log(`PR Number: ${prNumber}`);
          
          const { data: comments } = await github.pulls.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
          });
          console.log(`Comments: ${JSON.stringify(comments, null, 2)}`);

          
