name: Greetings

on:
 pull_request:
    branches:
      - release
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        script: |
          const PRContent = context.payload.pull_request
          console.log(`PR content: ${PRContent}`);
  
